sudo: required
language: php
php:
- 7.0.12
env:
  global:
  - secure: 1Ux2vWOGnL98jW9MEIQcvPjW0PcDF92hS4mPmsOzlmpzAWD6F3ZyZybzyosoVckPNdOTqrig2lLrr+LU8qFopzqW7NGgWiKALLPKGYrfe6QDWBM74E8JIVcbfUus8Lp21cH1z/qboUffW+IqDt9d0RoEB9uMa3n8p+xexJ4ATX0hkRwG57e9wu0O5mdo+ZXIf4pwiNxEBQrSxNl+dldSvf/DcYnbqDKwrdnrM0AaqJcZfbrqR7sovRYPyyadtDr42c2E73nRrXNWcEkLPHTbwZXawab1Znh0GkDQxhn8MuiYMb752eGcuT23DysX1bKjEmE4c6/hwHNLeTzoXf3PMDtHuKxxcdC3nGXzOqOyqGk+zZwonpwjfHMaB6c89LDx2Xl4aLTG3MVlFKpaoHuQMHY6saMCbO0OT+TK3AQ3KgdwhHn3Aa5Jhoqah0RMlEGfY1vdxhET+SToXJRJcZL97ugafNi1W9O3jWbrnBdkSnFktT/7ns0Y1mX/Mb3x2qXkGJIJBte1uTV35n7qrkMpkeZGA1hXo6PeuZGSylbwhhelqF4iOXum0n6qVvkUxrxxRhVPYt2lGZQ1pUWBgq/WEf2K5PRzhsNoSbjjN8AUriLULDhLoEMsZwYQ0S04KLuIPY7wcPMMs1/hI1HfTuURqCpC7HUsLxS8T/N5vra8ZbA=
  - secure: 1ig8lqNZHwbf7R8NU8t2/+7kEinUmTF48p/7o9AjUN9LjH59N1SfHEqyen5PCzX51zyrVPLiGLzNBdo/Fv5ngZx7S4cwWDdcgvWmOhBpsLe2ezboJ0j/bPT6v4Rvx2AEJMBUTvzCy547r0tZpSwv39JFK1JREiz9anCR07cfj/y4dESzSCuPHRTNpl+P8DgyYHz+bodAOsyd5jKm/xIe163oaAFWqC6yZyIeffhRfJuu5TrtGyG4YPLoPSMBcTvN0e/GsKnDhtHrB1Ku6mcE1SzIExoE/2ccc3NPBT99fflMtkVZqEkrGmh9e+dDZJ7UuDqM9SpevgM0bPxnfXf9vajHm2c6lCrztjrEySSKm+iofouJ7ezwJmsN4tCrQexwEADn+Jmrbe+dW2ZlZa1t6AtX06o/rvFIWO1THkeqc0T3LDOShsBF7+VABKI+FV2SdUXWt1JSKoxUNjuDhMjo9IeF7n7xwVFdWdkx4D2qh3cxZjZdx9wUOsqyqTdF79Fir51LYSiFnYv3nXo4VGH6k62sAVT90y1+oAGznF2Cr8dNTu/A7eSChIsd4thN0Z6LKkptdgct70nBRvUGeybvgqU5VhzIt8QIy051G99uB81qXoxew70LDbqq/DWssyFI8La98MPZFEPSMZvuiSN+h/f9YUygISnryciycX1mWyU=
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+/"
  - "/\\d+\\.\\d+/"
before_script:
- composer self-update -vvv
- composer install --no-interaction  -vvv
script: 
before_install:
- echo "zend.enable_gc = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "memory_limit -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
  fast_finish: true
after_success:
  - $(echo $REBUILD_SATIS)
  - TRAVIS_TOKEN=$(echo $TRAVIS_TOKEN) sh rebuild-satis.sh
  - ls -la
