sudo: required

language: php

php:
  - 7.0.12

env:

# Only watch the master branch and tagged release.
branches:
 only:
   - master
   - develop
   - /\d+\.\d+\.\d+/
   - /\d+\.\d+/

# Commands to be run before your environment runs.
before_script:
  - composer self-update -vvv
  - composer install --no-interaction  -vvv
  - composer update codacy/coverage --dev -vvv
  - composer dump-autoload -vvv

# Commands you want to run that will verify your build.
script:
  - vendor/bin/phpunit

#after_script:
#  - php vendor/bin/codacycoverage clover build/logs/clover.xml -v

before_install:
# Disable garbage collection and memory limits
  - echo "zend.enable_gc = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "memory_limit -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

after_success:
    
