sudo: required
language: php
php:
- 7.0.12
env:
  global:
  - secure: 1Ux2vWOGnL98jW9MEIQcvPjW0PcDF92hS4mPmsOzlmpzAWD6F3ZyZybzyosoVckPNdOTqrig2lLrr+LU8qFopzqW7NGgWiKALLPKGYrfe6QDWBM74E8JIVcbfUus8Lp21cH1z/qboUffW+IqDt9d0RoEB9uMa3n8p+xexJ4ATX0hkRwG57e9wu0O5mdo+ZXIf4pwiNxEBQrSxNl+dldSvf/DcYnbqDKwrdnrM0AaqJcZfbrqR7sovRYPyyadtDr42c2E73nRrXNWcEkLPHTbwZXawab1Znh0GkDQxhn8MuiYMb752eGcuT23DysX1bKjEmE4c6/hwHNLeTzoXf3PMDtHuKxxcdC3nGXzOqOyqGk+zZwonpwjfHMaB6c89LDx2Xl4aLTG3MVlFKpaoHuQMHY6saMCbO0OT+TK3AQ3KgdwhHn3Aa5Jhoqah0RMlEGfY1vdxhET+SToXJRJcZL97ugafNi1W9O3jWbrnBdkSnFktT/7ns0Y1mX/Mb3x2qXkGJIJBte1uTV35n7qrkMpkeZGA1hXo6PeuZGSylbwhhelqF4iOXum0n6qVvkUxrxxRhVPYt2lGZQ1pUWBgq/WEf2K5PRzhsNoSbjjN8AUriLULDhLoEMsZwYQ0S04KLuIPY7wcPMMs1/hI1HfTuURqCpC7HUsLxS8T/N5vra8ZbA=
  - secure: QYqgRLjG7SIAVnSoA/P/oSB/WuB13XIkxOFXDYS7gm7PS2f22848FORP9F5QFx2XK3/VOc48qImUoGNzz0PkEo7ME7ca7g3D2WNLwZrKb9ilKx8HN8haq0dFQ3txmWQ6K9uDHTZRUchazVbfLEjah7q3X1ppAJyIrtWnPrdJVkUm45946Oci5Cg1YBAwUDkFgsE+J3HONiVkzHHbmE0abkIuTIMtK/ZTLphTmg3F+OqXGY0QvN0Wd4v5RArVXudLYXxsPgt+n5sGl1w4YVS172Tn2p4A12E8sJk8QuJnjp79GVPItJf3+hYJxkmVPrEYWUCL+mdI783bim0w0nTgRWTT6KZs67w9oeH3+YjM+Mk4q+0WISThKqSdkp2c65w38VL7Z9NZKzLKPCU5gc03i8K8IHHHSjJ0cuF2P3U0eDjnIgF99mGf+8w9LDyDK2YtrpBEbfiG8kzDS4M38/ROjdQdMkb5NmihXTmJsCp49GfvW8a5+SaroPP09CD2ZYIRfUNNXGUqd1H5zNcfehJmW/Ak4XrLx04/6XsswjR+1JXAExB4mPshe1jEgt9uy6SFRz+V/niVya55PePBHqbvPbY/Mh8x6Rt3XIEQqvcJPw+3Z56wKQ7w5a0oAzGmhfcaJOUxVMxuqGyvpsa9lbjESw2M/VxXIc1dIQyiSRrdykw=
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+/"
  - "/\\d+\\.\\d+/"
before_script:
- composer self-update -vvv
- composer install --no-interaction  -vvv
script: 
before_install:
- echo "zend.enable_gc = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "memory_limit -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
  fast_finish: true
after_success:
- curl -o rebuild-satis.sh $REBUILD_SATIS_URL
- sh rebuild-satis.sh
